In [1]:
#Numpy is numerical python
import numpy
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [7]:
l= [2,3,4,5,4,5]
x = np.asarray(l)
print(x)
print(type(x))

[2 3 4 5 4 5]
<class 'numpy.ndarray'>


In [8]:
x = np.asarray(l,float)
print(x)
print(x.shape)

[2. 3. 4. 5. 4. 5.]
(6,)


In [10]:
#np two dimentional array
import numpy
import numpy as np
x = np.array(([1,2,3],[3,6,7]))
print(x)
print(x.shape)
print(x[0,0])
print(x[0,1])
print(x[0,2])
print(x[0,0:3])
print(x[1,0:3])
print(x[1,1:3])
print(x[0,0:])

[[1 2 3]
 [3 6 7]]
(2, 3)
1
2
3
[1 2 3]
[3 6 7]
[6 7]
[1 2 3]


In [16]:
#to print zero matrix
x = np.zeros((4,5),dtype = int)
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
#to print identity matrix
x = np.eye(4,4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
x = np.random.random((4,5))
print(x)

[[0.63601765 0.98454845 0.49395837 0.98361876 0.90394548]
 [0.89185927 0.29555232 0.00591555 0.75626597 0.1539448 ]
 [0.7000747  0.66355415 0.40713477 0.49201499 0.36101623]
 [0.97767146 0.27070526 0.41483447 0.52950526 0.80540113]]


In [29]:
#Reshaping the matrix 
x = np.array(([1,3,4],[2,4,5]))
print (x)
y = x.reshape(3,2)
print(y)

[[1 3 4]
 [2 4 5]]
[[1 3]
 [4 2]
 [4 5]]


In [31]:
a = np .empty([3,2],dtype=int)
print("empty array",a)

empty array [[1 3]
 [4 2]
 [4 5]]


In [33]:
#A matrix of ones
x = np.ones((3,3),dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
a = np.arange(5)
print(a)
b = np.arange(5)
print(b)
c = a + b
print("Additon of matrix",c, c+1)# broadcasting 

[0 1 2 3 4]
[0 1 2 3 4]
Additon of matrix [0 2 4 6 8] [1 3 5 7 9]


In [43]:
#Subtraction of two matrices
a = np.ones((2,2),dtype=int)
print(a)
b= np.array(([2,3],[22,4]))
print(b)
c = a-b
print("Subtraction of two matrix",c)

[[1 1]
 [1 1]]
[[ 2  3]
 [22  4]]
Subtraction of two matrix [[ -1  -2]
 [-21  -3]]


In [46]:
#Dot product of two matrices 
a = np.ones((2,3))
print(a)
b = np.ones((3,2))
print(b)
c = np.dot(a,b)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3. 3.]
 [3. 3.]]


In [54]:
#Multiplication of two matrices 
a = np.array(([5,2],[7,4]))
print(a)
b = np.array(([1,2],[3,4]))
print(b)
c = a*b
print(c)

[[5 2]
 [7 4]]
[[1 2]
 [3 4]]
[[ 5  4]
 [21 16]]


In [58]:
#Sum of elements of an array
a = np.ones((2,3))
b = a.sum()
print(b)
w = a.sum(axis=0)#Adding elemts in coloumns
print(w)
y = a.sum(axis=1)#Adding elements in rows 
print(y)

6.0
[2. 2. 2.]
[3. 3.]


In [60]:
x = np.array([[1,2,3],[23,33,45]])
print(x)
print(x[x>5])#Print elements which are greater than 5

[[ 1  2  3]
 [23 33 45]]
[23 33 45]


In [64]:
a = np.arange(0,60,5)#values in range 0 to 60(not 60) which are multiple of 5
print(a)
a = a.reshape(3,4)
print(a)
for i in np.nditer(a):
    print(i)

[ 0  5 10 15 20 25 30 35 40 45 50 55]
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [16]:
#Question 7
import numpy
import numpy as np
x = np.arange(2,11)
y = x.reshape(3,3)
print(x)
print(y)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [17]:
#Question 8
x = np.arange(1,10)
print(x)
x[5] = 19
print(x)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5 19  7  8  9]


In [20]:
#Question number 9//
x = np.arange(12,39)
print(x)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [22]:
#Question number 10
x = np.arange(0,11)
print(x)
x = x[::-1]
print(x)


[ 0  1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1  0]


In [27]:
#Question 11
x = np.asarray ([12,13,14,11,10],dtype=float)
print(x)

[12. 13. 14. 11. 10.]


In [36]:
#Question number 13
x = np.ones((6,6),dtype=int)
print(x)
x[1:-1,1:-1]=0
print(x)


[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [40]:
#Question number 14
x = np.ones((8,8),dtype=int)
print(x)
x[1::2,::2] = 0
x[::2,1::2] = 0
print(x)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [45]:
import numpy 
print(np.__version__)

1.15.1


In [ ]:
1